### ISSUE TITLE
Investigate if hardhat deployments work

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1438]
Apparently they should work since it's a straight jRPC interaction however, some users reported problems with it: https://github.com/codingwithmanny/zkevm-erc20

In the previous repo:

```bash
npm i
# copy .env.example into .env and set private key
./node_modules/.bin/hardhat  run scripts/deploy.ts;
```

**Comment by codingwithmanny** [comment]
# Steps To Reproduce:

## 1 - Setup & Install dependencies:

```bash
git clone https://github.com/codingwithmanny/zkevm-erc20;
cd zkevm-erc20;
pnpm install;
copy .env.example .env;
```

## 2 - Update Environment Variables

**File:** `./.env`

```txt
RPC_ZKEVM_URL="https://public.zkevm-test.net/"
WALLET_PRIVATE_KEY="<YOUR-WALLET-PRIVATE-KEY-DO-NOT-SHARE-WITH-ANYONE>"
```

## 3 - Ensure Contract Is Compiled

```bash
./node_modules/.bin/hardhat compile;
```

## 3A - (Optional) Ensure Tests Pass

```bash
./node_modules/.bin/hardhat test
```

## 4 - Deploy

```bash
./node_modules/.bin/hardhat run scripts/deploy.ts --network zkevm
```

**Error Output:**

```bash
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/path/to/zkevm-erc20/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/path/to/zkevm-erc20/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/path/to/zkevm-erc20/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (/path/to/zkevm-erc20/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/path/to/zkevm-erc20/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/path/to/zkevm-erc20/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Comment by codingwithmanny** [comment]
Just wanted to bump this @arnaubennassar
