### ISSUE TITLE
jRPC panics after unexpected response from executor

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1823]
```log
 {"level":"error","caller":"jsonrpc/server.go:400","msg":"failed to get balance from state:rpc error: code = ResourceExhausted desc =  %!s(MISSING)","pid":3527597,"version":"v0.0.3-RC17","stacktrace":"github.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponseWithData\n\t/opt/zkevm-node/jsonrpc/server.go:400\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponse\n\t/opt/zkevm-node/jsonrpc/server.go:395\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:150\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:140\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:132\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
 {"level":"info","caller":"jsonrpc/handler.go:134","msg":"failed call: [-32000]failed to get balance from state. Params: [\"0x0000000000000000000000000000000000000000\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":0}
 {"level":"debug","caller":"jsonrpc/handler.go:87","msg":"Current open connections 0","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":0}
 {"level":"debug","caller":"jsonrpc/handler.go:89","msg":"Current open connections 1","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":1}
 {"level":"debug","caller":"jsonrpc/handler.go:90","msg":"request params [\"0x010530c8066681d20412de14fbbfa21565956826\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":1}
 {"level":"debug","caller":"jsonrpc/handler.go:89","msg":"Current open connections 2","pid":3527597,"version":"v0.0.3-RC17","method":"eth_call","requestId":0}
 {"level":"debug","caller":"jsonrpc/handler.go:90","msg":"request params [{\"data\":\"0x70a082310000000000000000000000002338d574e875c3d53e56f007a57b5ea8a5ae37b3\",\"to\":\"0xfd33c1f149bf39b9fd45935d4ba1834a856d1922\"},\"0x240\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_call","requestId":0}
 {"level":"error","caller":"jsonrpc/server.go:400","msg":"failed to get balance from state:rpc error: code = ResourceExhausted desc =  %!s(MISSING)","pid":3527597,"version":"v0.0.3-RC17","stacktrace":"github.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponseWithData\n\t/opt/zkevm-node/jsonrpc/server.go:400\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponse\n\t/opt/zkevm-node/jsonrpc/server.go:395\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:150\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:140\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:132\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
 {"level":"info","caller":"jsonrpc/handler.go:134","msg":"failed call: [-32000]failed to get balance from state. Params: [\"0x010530c8066681d20412de14fbbfa21565956826\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":1}
 {"level":"debug","caller":"jsonrpc/handler.go:87","msg":"Current open connections 1","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":1}
 {"level":"debug","caller":"jsonrpc/handler.go:89","msg":"Current open connections 2","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":2}
 {"level":"debug","caller":"jsonrpc/handler.go:90","msg":"request params [\"0x85da99c8a7c2c95964c8efd687e95e632fc533d6\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":2}
 {"level":"error","caller":"jsonrpc/server.go:400","msg":"failed to get balance from state:rpc error: code = ResourceExhausted desc =  %!s(MISSING)","pid":3527597,"version":"v0.0.3-RC17","stacktrace":"github.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponseWithData\n\t/opt/zkevm-node/jsonrpc/server.go:400\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponse\n\t/opt/zkevm-node/jsonrpc/server.go:395\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:150\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:140\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:132\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
 {"level":"info","caller":"jsonrpc/handler.go:134","msg":"failed call: [-32000]failed to get balance from state. Params: [\"0x85da99c8a7c2c95964c8efd687e95e632fc533d6\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":2}
 {"level":"debug","caller":"jsonrpc/handler.go:87","msg":"Current open connections 1","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":2}
 {"level":"debug","caller":"jsonrpc/handler.go:89","msg":"Current open connections 2","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":3}
 {"level":"debug","caller":"jsonrpc/handler.go:90","msg":"request params [\"0x9fc5fa2e686930afb03802a5c3ce31833299e03f\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":3}
 {"level":"debug","caller":"state/helper.go:110","msg":"0 0 30000000 0xfD33C1f149BF39b9fD45935D4Ba1834a856D1922 0 36 1","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1291","msg":"internalProcessUnsignedTransaction[processBatchRequest.OldBatchNum]: 16","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1292","msg":"internalProcessUnsignedTransaction[processBatchRequest.From]: 0x1111111111111111111111111111111111111111","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1293","msg":"internalProcessUnsignedTransaction[processBatchRequest.OldStateRoot]: 0xd298a9c21da6855744cd26239f1c89cb1d4aa7b55e0e54716db72f5d0a2f6438","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1294","msg":"internalProcessUnsignedTransaction[processBatchRequest.globalExitRoot]: 0x502c6908036062957ce27f0c1de8aea2a1d659a44f7262139b26986c4ab5235a","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1295","msg":"internalProcessUnsignedTransaction[processBatchRequest.OldAccInputHash]: 0x0000000000000000000000000000000000000000000000000000000000000000","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1296","msg":"internalProcessUnsignedTransaction[processBatchRequest.EthTimestamp]: 1678751175","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1297","msg":"internalProcessUnsignedTransaction[processBatchRequest.Coinbase]: 0x85dA99c8a7C2C95964c8EfD687E95E632Fc533D6","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1298","msg":"internalProcessUnsignedTransaction[processBatchRequest.UpdateMerkleTree]: 0","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1299","msg":"internalProcessUnsignedTransaction[processBatchRequest.ChainId]: 1","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"debug","caller":"state/state.go:1300","msg":"internalProcessUnsignedTransaction[processBatchRequest.ForkId]: 2","pid":3527597,"version":"v0.0.3-RC17"}
 {"level":"error","caller":"jsonrpc/server.go:400","msg":"failed to get balance from state:rpc error: code = ResourceExhausted desc =  %!s(MISSING)","pid":3527597,"version":"v0.0.3-RC17","stacktrace":"github.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponseWithData\n\t/opt/zkevm-node/jsonrpc/server.go:400\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponse\n\t/opt/zkevm-node/jsonrpc/server.go:395\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:150\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:140\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:132\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
 {"level":"error","caller":"state/state.go:1719","msg":"error found in the executor: EXECUTOR_ERROR_UNSPECIFIED at 2023-03-13 23:46:17.843290016 +0000 UTC m=+1117.166840719 %!s(MISSING)","pid":3527597,"version":"v0.0.3-RC17","stacktrace":"github.com/0xPolygonHermez/zkevm-node/state.(*State).LogExecutorError\n\t/opt/zkevm-node/state/state.go:1719\ngithub.com/0xPolygonHermez/zkevm-node/state.(*State).internalProcessUnsignedTransaction\n\t/opt/zkevm-node/state/state.go:1309\ngithub.com/0xPolygonHermez/zkevm-node/state.(*State).ProcessUnsignedTransaction\n\t/opt/zkevm-node/state/state.go:1218\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:81\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:54\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:132\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
 {"level":"info","caller":"jsonrpc/handler.go:134","msg":"failed call: [-32000]failed to get balance from state. Params: [\"0x9fc5fa2e686930afb03802a5c3ce31833299e03f\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":3}
 {"level":"debug","caller":"jsonrpc/handler.go:87","msg":"Current open connections 1","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":3}
 {"level":"debug","caller":"jsonrpc/handler.go:89","msg":"Current open connections 2","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":4}
 {"level":"debug","caller":"jsonrpc/handler.go:90","msg":"request params [\"0xfd33c1f149bf39b9fd45935d4ba1834a856d1922\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":4}
 {"level":"error","caller":"jsonrpc/server.go:400","msg":"failed to get balance from state:rpc error: code = ResourceExhausted desc =  %!s(MISSING)","pid":3527597,"version":"v0.0.3-RC17","stacktrace":"github.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponseWithData\n\t/opt/zkevm-node/jsonrpc/server.go:400\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.rpcErrorResponse\n\t/opt/zkevm-node/jsonrpc/server.go:395\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:150\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).GetBalance\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:140\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:132\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
 {"level":"info","caller":"jsonrpc/handler.go:134","msg":"failed call: [-32000]failed to get balance from state. Params: [\"0xfd33c1f149bf39b9fd45935d4ba1834a856d1922\",\"0x242\"]","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":4}
 {"level":"debug","caller":"jsonrpc/handler.go:87","msg":"Current open connections 1","pid":3527597,"version":"v0.0.3-RC17","method":"eth_getBalance","requestId":4}
 {"level":"debug","caller":"jsonrpc/handler.go:87","msg":"Current open connections 0","pid":3527597,"version":"v0.0.3-RC17","method":"eth_call","requestId":0}
 2023/03/13 23:46:17 http: panic serving 10.10.67.44:40886: runtime error: invalid memory address or nil pointer dereference
 goroutine 8291 [running]:
 net/http.(*conn).serve.func1()
         /usr/local/go/src/net/http/server.go:1850 +0xbf
 panic({0x1409740, 0x2499a50})
         /usr/local/go/src/runtime/panic.go:890 +0x262
 github.com/0xPolygonHermez/zkevm-node/state.(*State).ProcessUnsignedTransaction(0x3c?, {0x194e168, 0xc00013a000}, 0xc000236340?, {0x11, 0x11, 0x11, 0x11, 0x11, 0x11, ...}, ...)
         /opt/zkevm-node/state/state.go:1222 +0xfd
 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call.func1({0x194e168, 0xc00013a000}, {0x1957ca0, 0xc000a9e570})
         /opt/zkevm-node/jsonrpc/endpoints_eth.go:81 +0x2c5
 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope(0x3?, {0x19637a8?, 0xc000472700?}, 0xc000d6abe0)
         /opt/zkevm-node/jsonrpc/dbtxmanager.go:20 +0x82
 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call(0x4?, 0xc000a835e0?, 0x2?)
         /opt/zkevm-node/jsonrpc/endpoints_eth.go:54 +0x5d
 reflect.Value.call({0xc0000b6400?, 0xc00052e0d8?, 0x55224c?}, {0x15dc7b6, 0x4}, {0xc0004f4910, 0x3, 0x542485?})
         /usr/local/go/src/reflect/value.go:584 +0x8c5
 reflect.Value.Call({0xc0000b6400?, 0xc00052e0d8?, 0xa0?}, {0xc0004f4910?, 0xc0009c2ee8?, 0x8?})
         /usr/local/go/src/reflect/value.go:368 +0xbc
 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle(0x24c4a40?, {{{0xc000825498, 0x3}, {0x137ebc0, 0x2309be0}, {0xc0008254b0, 0x8}, {0xc000dd4000, 0x91, 0xa0}}, ...})
         /opt/zkevm-node/jsonrpc/handler.go:132 +0xafa
 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest(0xc0003803c0, {0x194ce30, 0xc000394c40}, {0xc000ceac00?, 0xc0000838c8?, 0x1162f4a?})
         /opt/zkevm-node/jsonrpc/server.go:300 +0x2a5
 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle(0xc000472000?, {0x194ce30, 0xc000394c40}, 0xc000d8ab00)
         /opt/zkevm-node/jsonrpc/server.go:250 +0x5e9
 net/http.HandlerFunc.ServeHTTP(0xc000825425?, {0x194ce30?, 0xc000394c40?}, 0xc000382b00?)
         /usr/local/go/src/net/http/server.go:2109 +0x2f
 github.com/didip/tollbooth/v6.LimitHandler.func1({0x194ce30, 0xc000394c40}, 0xc0fc0b5270ff3a3b?)
         /root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311 +0x22c
 net/http.HandlerFunc.ServeHTTP(0xc000394c40?, {0x194ce30?, 0xc000394c40?}, 0x15e9c89?)
         /usr/local/go/src/net/http/server.go:2109 +0x2f
 net/http.(*ServeMux).ServeHTTP(0x0?, {0x194ce30, 0xc000394c40}, 0xc000d8ab00)
         /usr/local/go/src/net/http/server.go:2487 +0x149
 net/http.serverHandler.ServeHTTP({0x1947220?}, {0x194ce30, 0xc000394c40}, 0xc000d8ab00)
         /usr/local/go/src/net/http/server.go:2947 +0x30c
 net/http.(*conn).serve(0xc000cd2820, {0x194e1d8, 0xc0001e58f0})
         /usr/local/go/src/net/http/server.go:1991 +0x607
 created by net/http.(*Server).Serve
         /usr/local/go/src/net/http/server.go:3102 +0x4db
```

**Comment by jleeqn** [comment]
The error `-32000]failed to get balance from state.` still happen on zkEVM Node version: `v0.1.2`
```
Jul 24 07:11:51 zkevm-node[27116]: 2023-07-24T07:11:51.283Z        INFO        jsonrpc/handler.go:144        failed call: [-32000]failed to get balance from state. Params: ["0x68af128c601ef3109ef7542cd4b15dfcf2766e4a","latest"]        {"pid": 27116, "version": "v0.1.2", "method": "eth_getBalance", "requestId": 645011}
Jul 24 07:11:51 zkevm-node[27116]: 2023-07-24T07:11:51.284Z        INFO        jsonrpc/handler.go:144        failed call: [-32000]failed to get balance from state. Params: ["0xedc7c0a67c150b31740d1eff1ed26fa7c66eecf3","latest"]        {"pid": 27116, "version": "v0.1.2", "method": "eth_getBalance", "requestId": 645012}
```

**Comment by bap2pecs** [comment]
+1. this still happens to me today @tclemos @arnaubennassar

**Comment by tclemos** [comment]
@jleeqn and @bap2pecs we made some improvements and fixes to the network since then, could you please double-check if you are still facing the issues?

Before testing it, please make sure to run the versions specified here: https://github.com/0xPolygonHermez
These are the instructions to guide you while updating the environment to the specified versions: https://polygontechnology.notion.site/Mainnet-Beta-UPDATE-zkEVM-Node-version-0-3-0-or-to-0-2-5-e150867951cd46c088f6d6c03b2cb5db

**Comment by bap2pecs** [comment]
sorry for the late response but thanks @tclemos! I don't see this happening anymore
