### ISSUE TITLE
jRPC panic

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1852]
```
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4519188,"caller":"state/helper.go:109","msg":"0 0 30000000 0xe2194B52dFfB1E88eE269A73091f5DF72dC690c6 0 36 1","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4519434,"caller":"state/helper.go:113","msg":"Forced nonce: 0","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4519806,"caller":"state/state.go:1299","msg":"internalProcessUnsignedTransaction[processBatchRequest.OldBatchNum]: 144","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4519956,"caller":"state/state.go:1300","msg":"internalProcessUnsignedTransaction[processBatchRequest.From]: 0x1111111111111111111111111111111111111111","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.452007,"caller":"state/state.go:1301","msg":"internalProcessUnsignedTransaction[processBatchRequest.OldStateRoot]: 0xfa6fbcf8f676265eeab9687bdf6d1a729ca1cbe3439fb9450fa78231b9dca7ac","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4520183,"caller":"state/state.go:1302","msg":"internalProcessUnsignedTransaction[processBatchRequest.globalExitRoot]: 0x0000000000000000000000000000000000000000000000000000000000000000","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.452029,"caller":"state/state.go:1303","msg":"internalProcessUnsignedTransaction[processBatchRequest.OldAccInputHash]: 0xb83318100a5904a923fe172b0f573789ad690c0087a0ef2f82ea4489215958e1","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4520402,"caller":"state/state.go:1304","msg":"internalProcessUnsignedTransaction[processBatchRequest.EthTimestamp]: 1679025030","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4520514,"caller":"state/state.go:1305","msg":"internalProcessUnsignedTransaction[processBatchRequest.Coinbase]: 0x85dA99c8a7C2C95964c8EfD687E95E632Fc533D6","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4520626,"caller":"state/state.go:1306","msg":"internalProcessUnsignedTransaction[processBatchRequest.UpdateMerkleTree]: 0","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4520738,"caller":"state/state.go:1307","msg":"internalProcessUnsignedTransaction[processBatchRequest.ChainId]: 1","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4520848,"caller":"state/state.go:1308","msg":"internalProcessUnsignedTransaction[processBatchRequest.ForkId]: 2","pid":121437,"version":"v0.0.3-RC19"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"error","ts":1679025230.452919,"caller":"state/state.go:1313","msg":"error processing unsigned transaction  rpc error: code = ResourceExhausted desc = %!(EXTRA string=\n/opt/zkevm-node/log/log.go:140 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()\n/opt/zkevm-node/log/log.go:249 github.com/0xPolygonHermez/zkevm-node/log.Errorf()\n/opt/zkevm-node/state/state.go:1313 github.com/0xPolygonHermez/zkevm-node/state.(*State).internalProcessUnsignedTransaction()\n/opt/zkevm-node/state/state.go:1225 github.com/0xPolygonHermez/zkevm-node/state.(*State).ProcessUnsignedTransaction()\n/opt/zkevm-node/jsonrpc/endpoints_eth.go:77 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call.func1()\n/opt/zkevm-node/jsonrpc/dbtxmanager.go:20 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope()\n/opt/zkevm-node/jsonrpc/endpoints_eth.go:55 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call()\n/usr/local/go/src/reflect/value.go:584 reflect.Value.call()\n/usr/local/go/src/reflect/value.go:368 reflect.Value.Call()\n/opt/zkevm-node/jsonrpc/handler.go:141 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle()\n/opt/zkevm-node/jsonrpc/server.go:300 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest()\n/opt/zkevm-node/jsonrpc/server.go:250 github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle()\n/usr/local/go/src/net/http/server.go:2109 net/http.HandlerFunc.ServeHTTP()\n/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311 github.com/didip/tollbooth/v6.LimitHandler.func1()\n/usr/local/go/src/net/http/server.go:2109 net/http.HandlerFunc.ServeHTTP()\n/usr/local/go/src/net/http/server.go:2487 net/http.(*ServeMux).ServeHTTP()\n/usr/local/go/src/net/http/server.go:2947 net/http.serverHandler.ServeHTTP()\n/usr/local/go/src/net/http/server.go:1991 net/http.(*conn).serve()\n)","pid":121437,"version":"v0.0.3-RC19","stacktrace":"github.com/0xPolygonHermez/zkevm-node/state.(*State).internalProcessUnsignedTransaction\n\t/opt/zkevm-node/state/state.go:1313\ngithub.com/0xPolygonHermez/zkevm-node/state.(*State).ProcessUnsignedTransaction\n\t/opt/zkevm-node/state/state.go:1225\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call.func1\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:77\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope\n\t/opt/zkevm-node/jsonrpc/dbtxmanager.go:20\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call\n\t/opt/zkevm-node/jsonrpc/endpoints_eth.go:55\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:368\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle\n\t/opt/zkevm-node/jsonrpc/handler.go:141\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest\n\t/opt/zkevm-node/jsonrpc/server.go:300\ngithub.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle\n\t/opt/zkevm-node/jsonrpc/server.go:250\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/didip/tollbooth/v6.LimitHandler.func1\n\t/root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4530187,"caller":"jsonrpc/handler.go:89","msg":"Current open connections 0","pid":121437,"version":"v0.0.3-RC19","method":"eth_call","requestId":0}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: 2023/03/17 03:53:50 http: panic serving 10.10.74.42:56566: runtime error: invalid memory address or nil pointer dereference
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: goroutine 195 [running]:
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: net/http.(*conn).serve.func1()
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:1850 +0xbf
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: panic({0x1411100, 0x24a7f10})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/runtime/panic.go:890 +0x262
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/state.(*State).ProcessUnsignedTransaction(0x3c?, {0x1958528, 0xc000040070}, 0xc00047ccc0?, {0x11, 0x11, 0x11, 0x11, 0x11, 0x11, ...}, ...)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/state/state.go:1229 +0xfb
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call.func1({0x1958528, 0xc000040070}, {0x1962080, 0xc000a6eb70})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/jsonrpc/endpoints_eth.go:77 +0x29e
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope(0x3?, {0x196dbb0?, 0xc000218900?}, 0xc000368bb8)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/jsonrpc/dbtxmanager.go:20 +0x82
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call(0x4?, 0xc0007cc560?, 0x2?)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/jsonrpc/endpoints_eth.go:55 +0x5d
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: reflect.Value.call({0xc000386100?, 0xc00012c630?, 0x55224c?}, {0x15e5276, 0x4}, {0xc0009d2690, 0x3, 0x542485?})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/reflect/value.go:584 +0x8c5
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: reflect.Value.Call({0xc000386100?, 0xc00012c630?, 0xa0?}, {0xc0009d2690?, 0xc000a6eb28?, 0x8?})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/reflect/value.go:368 +0xbc
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle(0x24d2f80?, {{{0xc000a3e8a8, 0x3}, {0x13860e0, 0x2317c00}, {0xc000a3e8c0, 0x8}, {0xc000202140, 0x92, 0xa0}}, ...})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/jsonrpc/handler.go:141 +0xc4b
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleBatchRequest(0xc00046e1e0, 0xc0003be600, {0x19571f0, 0xc000454460}, {0xc000403600?, 0xe?, 0x40b3880000000000?})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/jsonrpc/server.go:300 +0x2db
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle(0xc000218500?, {0x19571f0, 0xc000454460}, 0xc0003be600)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /opt/zkevm-node/jsonrpc/server.go:250 +0x5e8
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: net/http.HandlerFunc.ServeHTTP(0xc000a3e845?, {0x19571f0?, 0xc000454460?}, 0xc000231f40?)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: github.com/didip/tollbooth/v6.LimitHandler.func1({0x19571f0, 0xc000454460}, 0xc0fd16f39906554c?)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /root/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311 +0x22c
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: net/http.HandlerFunc.ServeHTTP(0xc000454460?, {0x19571f0?, 0xc000454460?}, 0x15f0338?)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:2109 +0x2f
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: net/http.(*ServeMux).ServeHTTP(0x0?, {0x19571f0, 0xc000454460}, 0xc0003be600)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:2487 +0x149
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: net/http.serverHandler.ServeHTTP({0x19515e0?}, {0x19571f0, 0xc000454460}, 0xc0003be600)
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:2947 +0x30c
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: net/http.(*conn).serve(0xc000224a00, {0x1958598, 0xc00011b5c0})
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:1991 +0x607
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: created by net/http.(*Server).Serve
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]:         /usr/local/go/src/net/http/server.go:3102 +0x4db
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4571068,"caller":"jsonrpc/handler.go:91","msg":"Current open connections 1","pid":121437,"version":"v0.0.3-RC19","method":"eth_call","requestId":0}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.4571338,"caller":"jsonrpc/handler.go:92","msg":"request params [{\"data\":\"0xc87b56dd0000000000000000000000000000000000000000000000000000000000000147\",\"to\":\"0xe2194b52dffb1e88ee269a73091f5df72dc690c6\"},\"latest\"]","pid":121437,"version":"v0.0.3-RC19","method":"eth_call","requestId":0}
Mar 17 03:53:50 rpc-001.devnet03.zkevm.polygon.private zkevm-node[121437]: {"level":"debug","ts":1679025230.5103457,"caller":"state/helper.go:109","msg":"0 0 30000000 0xe2194B52dFfB1E88eE269A73091f5DF72dC690c6 0 36 1","pid":121437,"version":"v0.0.3-RC19"}
```

**Comment by tclemos** [comment]
Closed by #1885
