### ISSUE TITLE
JsonRPC: eth_call returns 502 error when params are empty

### ISSUE THREAD

**Issue by NikitosnikN** [0xPolygonHermez/zkevm-node#1853]
When I'm trying to call `eth_call` without params it RPC node (version: v0.0.3-RC21) returns 502 error with logs:

```
2023-03-17T11:21:23.625Z	INFO	db/logger.go:18	Query map[args:[] pid:1850 rowCount:1 sql:SELECT header, uncles, received_at FROM state.l2block b ORDER BY b.block_num DESC LIMIT 1 time:1.044938ms]	{"pid": 1, "version": ""}
2023-03-17T11:21:23.625Z	INFO	db/logger.go:18	Query map[args:[4355] pid:1850 rowCount:1 sql:SELECT encoded FROM state.transaction WHERE l2_block_num = $1 time:553.158µs]	{"pid": 1, "version": ""}
2023-03-17T11:21:24.041Z	DEBUG	jsonrpc/handler.go:91	Current open connections 1	{"pid": 1, "version": "", "method": "eth_call", "requestId": 1}
2023-03-17T11:21:24.041Z	DEBUG	jsonrpc/handler.go:92	request params []	{"pid": 1, "version": "", "method": "eth_call", "requestId": 1}
2023-03-17T11:21:24.042Z	INFO	db/logger.go:18	Exec map[args:[] commandTag:BEGIN pid:1850 sql:begin time:611.828µs]	{"pid": 1, "version": ""}
2023-03-17T11:21:24.042Z	DEBUG	jsonrpc/handler.go:89	Current open connections 0	{"pid": 1, "version": "", "method": "eth_call", "requestId": 1}
2023/03/17 11:21:24 http: panic serving 10.100.9.117:55632: runtime error: invalid memory address or nil pointer dereference
goroutine 260 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x13e63a0, 0x244bd90})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call.func1({0x1921d18, 0xc000050038}, {0x1929fa0, 0xc000b273e0})
	/src/jsonrpc/endpoints_eth.go:57 +0x65
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*dbTxManager).NewDbTxScope(0x3?, {0x1930838?, 0xc0001aa900?}, 0xc000c46ba0)
	/src/jsonrpc/dbtxmanager.go:20 +0x82
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*EthEndpoints).Call(0x4?, 0xc0004aee70?, 0x2?)
	/src/jsonrpc/endpoints_eth.go:55 +0x5d
reflect.Value.call({0xc0003be000?, 0xc0002ce190?, 0x54b7ad?}, {0x15b7bd1, 0x4}, {0xc00077d270, 0x3, 0x53c365?})
	/usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xc0003be000?, 0xc0002ce190?, 0x8?}, {0xc00077d270, 0x3, 0x3})
	/usr/local/go/src/reflect/value.go:339 +0xbf
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Handler).Handle(0x45?, {{{0xc0004aed10, 0x3}, {0x135d3a0, 0xc0004aecb8}, {0xc0004aec78, 0x8}, {0xc0004aecb0, 0x2, 0x8}}, ...})
	/src/jsonrpc/handler.go:141 +0xc5a
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handleSingleRequest(0xc000b1c2d0, 0xc0001aaf00, {0x1920c30, 0xc0007a0c40}, {0xc000439c00?, 0xd?, 0x40b3880000000000?})
	/src/jsonrpc/server.go:273 +0x1fb
github.com/0xPolygonHermez/zkevm-node/jsonrpc.(*Server).handle(0xc000274400?, {0x1920c30, 0xc0007a0c40}, 0xc0001aaf00)
	/src/jsonrpc/server.go:248 +0x5af
net/http.HandlerFunc.ServeHTTP(0xc0004ae2c5?, {0x1920c30?, 0xc0007a0c40?}, 0xc0003f56c0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/didip/tollbooth/v6.LimitHandler.func1({0x1920c30, 0xc0007a0c40}, 0x14798dcd75?)
	/go/pkg/mod/github.com/didip/tollbooth/v6@v6.1.2/tollbooth.go:311 +0x222
net/http.HandlerFunc.ServeHTTP(0x681467575?, {0x1920c30?, 0xc0007a0c40?}, 0xc000c045b0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1920c30, 0xc0007a0c40}, 0xc0001aaf00)
	/usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x191b080?}, {0x1920c30, 0xc0007a0c40}, 0xc0001aaf00)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003bba40, {0x1921d88, 0xc000435290})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

Steps to reproduce:

```
curl --request POST \
  --url RPC_URL \
  --header 'Content-Type: application/json' \
  --data '{
        "method": "eth_call",
        "params": [],
        "id": 1,
        "jsonrpc": "2.0"
}'
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

``` 

Other requests works fine

```
curl --request POST \
  --url NODE_URL \
  --header 'Content-Type: application/json' \
  --data '{
        "method": "eth_call",
        "params": ["not-valid"],
        "id": 1,
        "jsonrpc": "2.0"
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Invalid Params"}}
```

**Comment by NikitosnikN** [comment]
these issues might be connected, not sure if problem is the same

https://github.com/0xPolygonHermez/zkevm-node/issues/1852
