### ISSUE TITLE
Improve e2e group 8 (RPC debug_trace) to reduce the failing rate

### ISSUE THREAD

**Issue by joanestebanr** [0xPolygonHermez/zkevm-node#2760]
# Rationale
The highest rate of false failing of the e2e groups are:

group 10: 42%: already fixed  #2748
group 8: 12%
group 9: 10%
group 5: 10%
So, the next most important is group is 8 (RPC debug_trace)

There are 6 fails in the total of 12 PR analized:
* https://github.com/0xPolygonHermez/zkevm-node/pull/2730: 1 fail  error: index out of range
* https://github.com/0xPolygonHermez/zkevm-node/pull/2729: 1 fail error: index out of range
* https://github.com/0xPolygonHermez/zkevm-node/pull/2725: 1 fail error: index out of range
* https://github.com/0xPolygonHermez/zkevm-node/pull/2724: 1 fail error: fail to connect executor
* https://github.com/0xPolygonHermez/zkevm-node/pull/2713: 2 fail error: index out of range
# What cause the error?

### runtime error: index out of range [1] with length 1 [recovered]
* https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6655517721/job/18087108962 (running time: 13m 47s) `sc deployment by hash`
* https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6655517721/job/18085956444 (running time: 14m 27s) `sc deployment by hash`
* https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6690513097/job/18175982106 (running time: 14m18s) `eth transfer by hash`
* https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6691578512/job/18179045030 (running time 12m 29s) `erc20 transfer by number`
* https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6692120682/job/18180666975 (running time 14m 14s) ` sc deployment by hash`
```
023-10-26T15:03:39.458Z	DEBUG	e2e-group8/debug_calltracer_test.go:374	tx sent: 0x5b01ecd1c4fd80b31c7e786bff45392a9b7a5c8599b046c6be8b4cdc08b5b836	{"pid": 24077, "version": "v0.1.0"}
2023-10-26T15:03:40.462Z	DEBUG	operations/wait.go:99	Transaction successfully mined: 0x5b01ecd1c4fd80b31c7e786bff45392a9b7a5c8599b046c6be8b4cdc08b5b836	{"pid": 24077, "version": "v0.1.0"}
--- FAIL: TestDebugTraceBlockCallTracer (69.28s)
    --- PASS: TestDebugTraceBlockCallTracer/eth_transfer_by_number (3.06s)
    --- PASS: TestDebugTraceBlockCallTracer/sc_deployment_by_number (3.06s)
    --- PASS: TestDebugTraceBlockCallTracer/sc_call_by_number (6.37s)
    --- PASS: TestDebugTraceBlockCallTracer/erc20_transfer_by_number (10.14s)
    --- PASS: TestDebugTraceBlockCallTracer/eth_transfer_by_hash (3.04s)
    --- FAIL: TestDebugTraceBlockCallTracer/sc_deployment_by_hash (3.06s)
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 2646 [running]:
testing.tRunner.func1.2({0x1dc57e0, 0xc00024cb70})
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1545 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1548 +0x630
panic({0x1dc57e0?, 0xc00024cb70?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:[920](https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6655517721/job/18087108962#step:6:921) +0x270
github.com/0xPolygonHermez/zkevm-node/ci/e2e-group8.TestDebugTraceBlockCallTracer.func3(0x0?)
	/home/runner/work/zkevm-node/zkevm-node/ci/e2e-group8/debug_calltracer_test.go:420 +0x1285
testing.tRunner(0xc000303520, 0xc00062c780)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1298
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1648 +0x82b
FAIL	github.com/0xPolygonHermez/zkevm-node/ci/e2e-group8	419.300s
FAIL
```

### executor/client.go:47	fail to dial: context deadline exceeded
* https://github.com/0xPolygonHermez/zkevm-node/actions/runs/6690314613/job/18175393484 (10m 43s)

```
2023-10-30T08:54:15.942Z	FATAL	executor/client.go:47	fail to dial: context deadline exceeded%!(EXTRA string=
/home/runner/work/zkevm-node/zkevm-node/log/log.go:140 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/home/runner/work/zkevm-node/zkevm-node/log/log.go:242 github.com/0xPolygonHermez/zkevm-node/log.Fatalf()
/home/runner/work/zkevm-node/zkevm-node/state/runtime/executor/client.go:47 github.com/0xPolygonHermez/zkevm-node/state/runtime/executor.NewExecutorClient()
/home/runner/work/zkevm-node/zkevm-node/test/operations/manager.go:467 github.com/0xPolygonHermez/zkevm-node/test/operations.initState()
/home/runner/work/zkevm-node/zkevm-node/test/operations/manager.go:103 github.com/0xPolygonHermez/zkevm-node/test/operations.NewManager()
/home/runner/work/zkevm-node/zkevm-node/ci/e2e-group8/debug_calltracer_test.go:43 github.com/0xPolygonHermez/zkevm-node/ci/e2e-group8.TestDebugTraceTransactionCallTracer()
/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595 testing.tRunner()
)	{"pid": 24124, "version": "v0.1.0"}
github.com/0xPolygonHermez/zkevm-node/state/runtime/executor.NewExecutorClient
	/home/runner/work/zkevm-node/zkevm-node/state/runtime/executor/client.go:47
github.com/0xPolygonHermez/zkevm-node/test/operations.initState
	/home/runner/work/zkevm-node/zkevm-node/test/operations/manager.go:467
github.com/0xPolygonHermez/zkevm-node/test/operations.NewManager
	/home/runner/work/zkevm-node/zkevm-node/test/operations/manager.go:103
github.com/0xPolygonHermez/zkevm-node/ci/e2e-group8.TestDebugTraceTransactionCallTracer
	/home/runner/work/zkevm-node/zkevm-node/ci/e2e-group8/debug_calltracer_test.go:43
testing.tRunner
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595
FAIL	github.com/0xPolygonHermez/zkevm-node/ci/e2e-group8	143.372s
FAIL
```

**Comment by joanestebanr** [comment]
Sometimes a L1 block could contain more that one tx. In that case the test fails, now match the tx that we want to check in the response of `debug_traceBlockByNumber` or `debug_traceBlockByHash`

**Comment by lyh169** [comment]
Hi, when fix the group 5  (RPC debug_trace), because the reason that group 5 and the group 8 run ci faild is same.
