### ISSUE TITLE
The e2e group 5 TestDebugTraceBlock, and group 8 TestDebugTraceBlockCallTracer probability fail

### ISSUE THREAD

**Issue by lyh169** [0xPolygonHermez/zkevm-node#2775]
# Rationale

The `TestDebugTraceBlock` of e2e group 5 and the `TestDebugTraceBlockCallTracer` have a  probability run fail ;

```
panic: runtime error: index out of range [1] with length 1 [recovered]
[996](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:997)
	panic: runtime error: index out of range [1] with length 1
[997](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:998)

[998](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:999)
goroutine 2856 [running]:
[999](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1000)
testing.tRunner.func1.2({0x1da0120, 0xc0003149a8})
[1000](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1001)
	/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1396 +0x372
[1001](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1002)
testing.tRunner.func1()
[1002](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1003)
	/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1399 +0x5f0
[1003](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1004)
panic({0x1da0120, 0xc0003149a8})
[1004](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1005)
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:890 +0x262
[1005](https://github.com/okx/Xgon-node/actions/runs/6820547258/job/18549614419?pr=39#step:6:1006)
github.com/0xPolygonHermez/zkevm-node/ci/e2e-group8.TestDebugTraceBlockCallTracer.func3(0x0?)
```

# Implementation
 The L1 block maybe contain more that one tx. but  the L2 block have one tx in compare block, In that case the test fails, so can not direct compare between L1 and L2 by  get the data from debug_traceBlockByNumber or debug_traceBlockByHash。

**Comment by joanestebanr** [comment]
Thanks you for the issue!, but is already duplicated #2760
