### ISSUE TITLE
zkevm-sync fails to start

### ISSUE THREAD

**Issue by JiamingSuper** [0xPolygonHermez/zkevm-node#2877]
```
2023-12-04 23:30:36 2023-12-04T15:30:36.816Z    ERROR   synchronizer/synchronizer.go:1269       error storing batch 1. Error: unsupported fork id
2023-12-04 23:30:36 /src/log/log.go:142 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
2023-12-04 23:30:36 /src/log/log.go:217 github.com/0xPolygonHermez/zkevm-node/log.Error()
2023-12-04 23:30:36 /src/synchronizer/synchronizer.go:1269 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).setInitialBatch()
2023-12-04 23:30:36 /src/synchronizer/synchronizer.go:266 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
2023-12-04 23:30:36 /src/cmd/run.go:323 main.runSynchronizer()
2023-12-04 23:30:36     {"pid": 1, "version": "v0.3.20-62-ge145e31a"}
2023-12-04 23:30:36 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).setInitialBatch
2023-12-04 23:30:36     /src/synchronizer/synchronizer.go:1269
2023-12-04 23:30:36 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
2023-12-04 23:30:36     /src/synchronizer/synchronizer.go:266
2023-12-04 23:30:36 main.runSynchronizer
2023-12-04 23:30:36     /src/cmd/run.go:323
2023-12-04 23:30:36 panic: runtime error: index out of range [0] with length 0
2023-12-04 23:30:36 
2023-12-04 23:30:36 goroutine 149 [running]:
2023-12-04 23:30:36 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync(0xc000310c40)
2023-12-04 23:30:36     /src/synchronizer/synchronizer.go:268 +0x2a05
2023-12-04 23:30:36 main.runSynchronizer({0x1, 0x0, 0x0, {{0xc0003f5a90, 0xb}, {0xc0003f5aa0, 0x5}, {0xc000694990, 0x1, 0x1}}, ...}, ...)
2023-12-04 23:30:36     /src/cmd/run.go:323 +0x5b2
2023-12-04 23:30:36 created by main.start in goroutine 1
2023-12-04 23:30:36     /src/cmd/run.go:223 +0x1c69
```

**Comment by obynonwane** [comment]
It seems you have not updated your node to the recent update
