### ISSUE TITLE
Aggregator panic

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#973]
```
zkevm-aggregator                | 2022-08-01T07:49:50Z  INFO    aggregator/aggregator.go:122    sending verified proof to the ethereum smart contract, batchNumber%!(EXTRA uint64=1)
zkevm-aggregator                | 2022-08-01T07:49:50Z  INFO    aggregator/aggregator.go:130    proof for the batch was send, batchNumber: 1
zkevm-aggregator                | 2022-08-01T07:49:50Z  INFO    aggregator/aggregator.go:77     checking if network is synced
zkevm-aggregator                | 2022-08-01T07:49:50Z  INFO    aggregator/aggregator.go:83     network is synced, getting batch to verify
zkevm-aggregator                | 2022-08-01T07:49:50Z  INFO    aggregator/aggregator.go:170    batch with number 1 was already sent, but not yet consolidated by synchronizer
zkevm-aggregator                | panic: runtime error: invalid memory address or nil pointer dereference
zkevm-aggregator                | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbb830a]
zkevm-aggregator                | 
zkevm-aggregator                | goroutine 29 [running]:
zkevm-aggregator                | github.com/0xPolygonHermez/zkevm-node/aggregator.(*Aggregator).tryVerifyBatch(0xc0004fde38, {0x11c3a30, 0xc000036060}, 0xf0e820)
zkevm-aggregator                |       /src/aggregator/aggregator.go:89 +0x12a
zkevm-aggregator                | github.com/0xPolygonHermez/zkevm-node/aggregator.(*Aggregator).Start(0xc0004fde38, {0x11c3a30, 0xc000036060})
zkevm-aggregator                |       /src/aggregator/aggregator.go:72 +0x87
zkevm-aggregator                | main.runAggregator({0x11c3a30, 0xc000036060}, {{0x2540be400}, {0x12a05f200}, {0xc000366ef0, 0x9}, {0xc0003944a0}, {0x0}}, 0xc00017d360, 0xc00017d450, ...)
zkevm-aggregator                |       /src/cmd/run.go:190 +0x36f
zkevm-aggregator                | created by main.start
zkevm-aggregator                |       /src/cmd/run.go:92 +0xd8f
```

**Comment by arnaubennassar** [comment]
closed by #983
